import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;700&family=Great+Vibes&family=Indie+Flower&family=Pacifico&family=Playfair+Display:wght@400;700&family=Cinzel:wght@400;700&family=Allura&family=Satisfy&family=Lobster&family=Tangerine:wght@400;700&family=Alex+Brush&family=Amatic+SC:wght@400;700&family=Architects+Daughter&family=Caveat:wght@400;700&family=Comforter&family=Cookie&family=Courgette&family=Damion&family=Grand+Hotel&family=Homemade+Apple&family=Kalam:wght@400;700&family=Kaushan+Script&family=Love+Ya+Like+A+Sister&family=Marck+Script&family=Merienda:wght@400;700&family=Norican&family=Oleo+Script:wght@400;700&family=Parisienne&family=Patrick+Hand&family=Permanent+Marker&family=Playball&family=Qwigley&family=Redressed&family=Reenie+Beanie&family=Rochester&family=Rouge+Script&family=Sacramento&family=Shadows+Into+Light&family=Sofia&family=Waiting+for+the+Sunrise&family=Yellowtail&family=Zeyada&family=Montserrat:wght@400;700&family=Poppins:wght@400;700&family=Raleway:wght@400;700&family=Oswald:wght@400;700&family=Ubuntu:wght@400;700&family=Lato:wght@400;700&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
